'use client';

import { useState, useEffect, useRef } from 'react';
import { usePet } from '@/context/PetContext';
import { SHOP_PRODUCTS, DEFAULT_PHOTO } from '@/lib/constants';
import { Dog, Sparkles, Download, RefreshCw } from 'lucide-react';

export default function Shop() {
  const { state, aiConfigured, saveProductPreview } = usePet();
  const [generating, setGenerating] = useState<string | null>(null);
  const [generatedImage, setGeneratedImage] = useState<{ image: string; productName: string } | null>(null);
  const [autoGenerating, setAutoGenerating] = useState(false);
  const hasAutoGenerated = useRef(false);

  const hasPhoto = state.pet?.photo && state.pet.photo !== DEFAULT_PHOTO;

  // Auto-generate images when user has photo and enters the shop
  useEffect(() => {
    const autoGenerateImages = async () => {
      if (!hasPhoto || !aiConfigured || !state.pet || hasAutoGenerated.current) return;

      // Check if we already have previews for all products
      const missingPreviews = SHOP_PRODUCTS.filter(p => !state.productPreviews[p.id]);
      if (missingPreviews.length === 0) return;

      hasAutoGenerated.current = true;
      setAutoGenerating(true);

      // Generate images for products without previews (one at a time to avoid overload)
      for (const product of missingPreviews) {
        try {
          const res = await fetch('/api/ai/pet-with-product', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              petName: state.pet.name,
              petBreed: state.pet.breed,
              productName: product.name,
              productDescription: product.description,
            }),
          });

          const data = await res.json();
          if (data.image) {
            saveProductPreview(product.id, data.image);
          }
        } catch (error) {
          console.error(`Failed to generate image for ${product.name}:`, error);
        }
      }

      setAutoGenerating(false);
    };

    autoGenerateImages();
  }, [hasPhoto, aiConfigured, state.pet, state.productPreviews, saveProductPreview]);

  const handleGenerateImage = async (productId: string, productName: string, productDescription: string) => {
    if (!state.pet) return;

    setGenerating(productId);

    try {
      const res = await fetch('/api/ai/pet-with-product', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          petName: state.pet.name,
          petBreed: state.pet.breed,
          productName,
          productDescription,
        }),
      });

      const data = await res.json();
      console.log('API response:', data);

      if (data.image) {
        saveProductPreview(productId, data.image);
        setGeneratedImage({ image: data.image, productName });
      } else {
        const errorMsg = data.details || data.error || 'Erro desconhecido';
        alert(`Não foi possível gerar a imagem: ${errorMsg}`);
      }
    } catch (error: any) {
      console.error('Failed to generate image:', error);
      alert(`Erro ao gerar imagem: ${error?.message || 'Erro de rede'}`);
    } finally {
      setGenerating(null);
    }
  };

  return (
    <div className="space-y-4">
      {/* Shop Header - Liquid Glass with gradient */}
      <div className="glass-card p-4 animate-fadeInUp relative overflow-hidden">
        {/* Gradient overlay */}
        <div className="absolute inset-0 bg-gradient-to-br from-purple-500/10 via-transparent to-pink-500/10 pointer-events-none"></div>

        <div className="relative z-10 flex items-center gap-4">
          {/* Pet avatar with liquid ring */}
          <div className="liquid-avatar-ring">
            <div className="w-14 h-14 rounded-full bg-[var(--background)] overflow-hidden flex items-center justify-center">
              {hasPhoto ? (
                <img src={state.pet?.photo || ''} alt={state.pet?.name} className="w-full h-full object-cover" />
              ) : (
                <Dog className="w-7 h-7 text-gray-400" />
              )}
            </div>
          </div>
          <div>
            <h3 className="font-semibold gradient-text">Presentes para {state.pet?.name || 'seu pet'}!</h3>
            <p className="text-sm text-gray-400">
              {autoGenerating ? (
                <span className="flex items-center gap-2">
                  <RefreshCw className="w-3 h-3 animate-spin text-purple-400" />
                  <span className="text-purple-300">Gerando previews com IA...</span>
                </span>
              ) : hasPhoto ? (
                'Veja como ficaria com cada brinquedo!'
              ) : (
                'Adicione uma foto para ver previews com IA'
              )}
            </p>
          </div>
        </div>
      </div>

      {/* Products - Liquid Glass Cards */}
      <div className="space-y-3">
        {SHOP_PRODUCTS.map((product, index) => {
          const hasPreview = !!state.productPreviews[product.id];
          const previewImg = state.productPreviews[product.id];
          const isGenerating = generating === product.id;

          return (
            <div
              key={product.id}
              className="space-y-2 animate-fadeInUp"
              style={{ animationDelay: `${index * 100}ms` }}
            >
              <a
                href={product.link}
                target="_blank"
                rel="noopener noreferrer"
                className="glass-task flex items-center gap-3 p-3 group"
              >
                {/* Product image with glow effect */}
                <div className="w-16 h-16 rounded-xl bg-white/90 overflow-hidden flex-shrink-0 relative shadow-lg group-hover:shadow-purple-500/20 transition-shadow duration-300">
                  <img
                    src={hasPreview ? previewImg : product.image}
                    alt={product.name}
                    className="w-full h-full object-cover"
                  />
                  {hasPreview && (
                    <div className="absolute bottom-0 right-0 text-xs bg-gradient-to-r from-indigo-500 to-purple-500 px-1.5 py-0.5 rounded-tl-lg text-white font-medium">
                      ✨ IA
                    </div>
                  )}
                </div>

                <div className="flex-1 min-w-0 relative z-10">
                  <h4 className="font-medium text-sm group-hover:text-white transition-colors">{product.name}</h4>
                  <p className="text-xs text-gray-400 line-clamp-1">{product.description}</p>
                  <span className="text-emerald-400 font-bold">{product.price}</span>
                </div>

                {/* Badge */}
                <div className="absolute top-2 right-2 text-xs px-2 py-1 bg-gradient-to-r from-purple-500/20 to-pink-500/20 rounded-full border border-purple-500/30 text-purple-300">
                  {product.badge}
                </div>
              </a>

              {aiConfigured && (
                <button
                  onClick={() => handleGenerateImage(product.id, product.name, product.description)}
                  disabled={isGenerating || autoGenerating}
                  className="w-full glass-button flex items-center justify-center gap-2 py-2.5 px-4 rounded-xl text-sm transition-all disabled:opacity-50 group"
                >
                  {isGenerating ? (
                    <>
                      <div className="w-4 h-4 border-2 border-purple-400 border-t-transparent rounded-full animate-spin" />
                      <span className="text-purple-300">Gerando preview...</span>
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-4 h-4 text-purple-400 group-hover:text-purple-300 transition-colors" />
                      <span className="text-purple-300 group-hover:text-white transition-colors">
                        {hasPreview ? 'Gerar nova imagem' : `Ver ${state.pet?.name || 'pet'} com esse!`}
                      </span>
                    </>
                  )}
                </button>
              )}
            </div>
          );
        })}
      </div>

      <p className="text-center text-xs text-gray-500 pt-2">
        Comprando aqui você ajuda o PetCare! 💜
      </p>

      {/* Generated Image Modal - Liquid Glass */}
      {generatedImage && (
        <div
          className="fixed inset-0 glass-backdrop flex items-center justify-center z-50 p-4 animate-fadeIn"
          onClick={() => setGeneratedImage(null)}
        >
          <div
            className="glass-card p-5 max-w-sm w-full animate-fadeInUp"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Image with glow effect */}
            <div className="relative rounded-2xl overflow-hidden mb-4 shadow-2xl shadow-purple-500/20">
              <img src={generatedImage.image} alt={generatedImage.productName} className="w-full" />
              <div className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent"></div>
            </div>

            <h3 className="text-center font-bold text-lg gradient-text mb-1">{state.pet?.name} adorou! 🎉</h3>
            <p className="text-center text-sm text-gray-400 mb-5">Imagem salva na loja!</p>

            <div className="flex gap-3">
              <button
                onClick={() => setGeneratedImage(null)}
                className="flex-1 py-3 glass-button rounded-xl hover:bg-white/10 transition-all font-medium"
              >
                Fechar
              </button>
              <a
                href={generatedImage.image}
                download={`${state.pet?.name}-${generatedImage.productName}.png`}
                className="flex-1 py-3 bg-gradient-to-r from-indigo-500 to-purple-500 rounded-xl hover:from-indigo-400 hover:to-purple-400 transition-all flex items-center justify-center gap-2 font-medium shadow-lg shadow-indigo-500/30"
              >
                <Download className="w-4 h-4" />
                Baixar
              </a>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
