'use client';

import { useState, useEffect, useRef } from 'react';
import { usePet } from '@/context/PetContext';
import { SHOP_PRODUCTS, DEFAULT_PHOTO } from '@/lib/constants';
import { Clock, Sparkles, Download, RefreshCw, Package, Upload, ImagePlus, X, Camera, Link2, Plus, Trash2, ExternalLink, Loader2 } from 'lucide-react';
import LinkPreview from './LinkPreview';

// Product image with fallback
function ProductImage({ src, alt, hasPreview }: { src: string; alt: string; hasPreview: boolean }) {
  const [error, setError] = useState(false);
  const [loaded, setLoaded] = useState(false);

  if (error || !src) {
    return (
      <div className="w-full h-full flex items-center justify-center bg-gradient-to-br from-indigo-500/20 to-purple-500/20">
        <Package className="w-6 h-6 text-indigo-400" />
      </div>
    );
  }

  return (
    <>
      {!loaded && (
        <div className="absolute inset-0 flex items-center justify-center bg-[var(--background-secondary)]">
          <div className="w-5 h-5 border-2 border-indigo-400 border-t-transparent rounded-full animate-spin" />
        </div>
      )}
      <img
        src={src}
        alt={alt}
        className={`w-full h-full object-cover transition-opacity duration-300 ${loaded ? 'opacity-100' : 'opacity-0'}`}
        onLoad={() => setLoaded(true)}
        onError={() => setError(true)}
      />
    </>
  );
}

export default function Shop() {
  const { state, aiConfigured, saveProductPreview, addCustomProduct, removeCustomProduct, getCachedImageUrl, preloadProductImages } = usePet();
  const [generating, setGenerating] = useState<string | null>(null);
  const [generatedImage, setGeneratedImage] = useState<{ image: string; productName: string } | null>(null);
  const [autoGenerating, setAutoGenerating] = useState(false);
  const hasAutoGenerated = useRef(false);

  // Status de pré-carregamento
  const isPreloading = state.isPreloadingImages;
  const hasCachedImages = Object.keys(state.cachedProductImages).length > 0;

  // Estados para upload de imagem do produto
  const [productImageModal, setProductImageModal] = useState<{ productId: string; productName: string } | null>(null);
  const [customProductImage, setCustomProductImage] = useState<string | null>(null);
  const [combiningImages, setCombiningImages] = useState(false);
  const productImageInputRef = useRef<HTMLInputElement>(null);

  // Estados para adicionar link do Mercado Livre
  const [showAddLinkModal, setShowAddLinkModal] = useState(false);
  const [linkUrl, setLinkUrl] = useState('');
  const [loadingLink, setLoadingLink] = useState(false);
  const [linkError, setLinkError] = useState<string | null>(null);
  const [linkPreviewData, setLinkPreviewData] = useState<{
    title: string;
    description: string;
    image: string;
    price?: string;
  } | null>(null);

  const hasPhoto = state.pet?.photo && state.pet.photo !== DEFAULT_PHOTO;

  // Auto-generate images when user has photo and enters the shop
  useEffect(() => {
    const autoGenerateImages = async () => {
      if (!hasPhoto || !aiConfigured || !state.pet || hasAutoGenerated.current) return;

      // Check if we already have previews for all products
      const missingPreviews = SHOP_PRODUCTS.filter(p => !state.productPreviews[p.id]);
      if (missingPreviews.length === 0) return;

      hasAutoGenerated.current = true;
      setAutoGenerating(true);

      // Generate images for products without previews (one at a time to avoid overload)
      for (const product of missingPreviews) {
        try {
          const res = await fetch('/api/ai/pet-with-product', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              petName: state.pet.name,
              petBreed: state.pet.breed,
              productName: product.name,
              productDescription: product.description,
            }),
          });

          const data = await res.json();
          if (data.image) {
            saveProductPreview(product.id, data.image);
          }
        } catch (error) {
          console.error(`Failed to generate image for ${product.name}:`, error);
        }
      }

      setAutoGenerating(false);
    };

    autoGenerateImages();
  }, [hasPhoto, aiConfigured, state.pet, state.productPreviews, saveProductPreview]);

  const handleGenerateImage = async (productId: string, productName: string, productDescription: string) => {
    if (!state.pet) return;

    setGenerating(productId);

    try {
      const res = await fetch('/api/ai/pet-with-product', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          petName: state.pet.name,
          petBreed: state.pet.breed,
          productName,
          productDescription,
        }),
      });

      const data = await res.json();
      console.log('API response:', data);

      if (data.image) {
        saveProductPreview(productId, data.image);
        setGeneratedImage({ image: data.image, productName });
      } else {
        const errorMsg = data.details || data.error || 'Erro desconhecido';
        alert(`Não foi possível gerar a imagem: ${errorMsg}`);
      }
    } catch (error: any) {
      console.error('Failed to generate image:', error);
      alert(`Erro ao gerar imagem: ${error?.message || 'Erro de rede'}`);
    } finally {
      setGenerating(null);
    }
  };

  // Handler para upload de imagem do produto
  const handleProductImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onloadend = () => {
      const result = reader.result as string;
      // Otimiza a imagem antes de armazenar
      optimizeImage(result).then(setCustomProductImage);
    };
    reader.readAsDataURL(file);
  };

  // Otimiza imagem redimensionando
  const optimizeImage = (dataUrl: string): Promise<string> => {
    return new Promise((resolve) => {
      const img = new Image();
      img.onload = () => {
        const canvas = document.createElement('canvas');
        const maxSize = 512;
        let { width, height } = img;

        if (width > height && width > maxSize) {
          height = (height * maxSize) / width;
          width = maxSize;
        } else if (height > maxSize) {
          width = (width * maxSize) / height;
          height = maxSize;
        }

        canvas.width = width;
        canvas.height = height;
        const ctx = canvas.getContext('2d');
        ctx?.drawImage(img, 0, 0, width, height);
        resolve(canvas.toDataURL('image/jpeg', 0.85));
      };
      img.src = dataUrl;
    });
  };

  // Handler para combinar imagens (pet + produto)
  const handleCombineImages = async () => {
    if (!state.pet?.photo || !customProductImage || !productImageModal) return;

    setCombiningImages(true);

    try {
      const res = await fetch('/api/ai/combine-images', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          petImage: state.pet.photo,
          productImage: customProductImage,
          petName: state.pet.name,
          petBreed: state.pet.breed,
          productName: productImageModal.productName,
        }),
      });

      const data = await res.json();

      if (data.image) {
        saveProductPreview(productImageModal.productId, data.image);
        setGeneratedImage({ image: data.image, productName: productImageModal.productName });
        setProductImageModal(null);
        setCustomProductImage(null);
      } else {
        const errorMsg = data.details || data.error || 'Erro desconhecido';
        alert(`Não foi possível combinar as imagens: ${errorMsg}`);
      }
    } catch (error: any) {
      console.error('Failed to combine images:', error);
      alert(`Erro ao combinar imagens: ${error?.message || 'Erro de rede'}`);
    } finally {
      setCombiningImages(false);
    }
  };

  // Abre modal para upload de imagem do produto
  const openProductImageModal = (productId: string, productName: string) => {
    setCustomProductImage(null);
    setProductImageModal({ productId, productName });
  };

  // Busca preview do link do Mercado Livre
  const fetchLinkPreview = async () => {
    if (!linkUrl.trim()) return;

    // Valida se é um link do Mercado Livre
    if (!linkUrl.includes('mercadolivre.com') && !linkUrl.includes('mercadolibre.com')) {
      setLinkError('Cole um link do Mercado Livre');
      return;
    }

    setLoadingLink(true);
    setLinkError(null);
    setLinkPreviewData(null);

    try {
      const res = await fetch('/api/link-preview', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: linkUrl }),
      });

      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error || 'Erro ao buscar preview');
      }

      setLinkPreviewData({
        title: data.title,
        description: data.description,
        image: data.image,
        price: data.price,
      });
    } catch (err: any) {
      setLinkError(err.message || 'Erro ao buscar preview');
    } finally {
      setLoadingLink(false);
    }
  };

  // Adiciona o produto customizado
  const handleAddCustomProduct = () => {
    if (!linkPreviewData) return;

    addCustomProduct({
      url: linkUrl,
      title: linkPreviewData.title,
      description: linkPreviewData.description,
      image: linkPreviewData.image,
      price: linkPreviewData.price,
    });

    // Reset modal state
    setShowAddLinkModal(false);
    setLinkUrl('');
    setLinkPreviewData(null);
    setLinkError(null);
  };

  // Reset modal ao fechar
  const closeAddLinkModal = () => {
    setShowAddLinkModal(false);
    setLinkUrl('');
    setLinkPreviewData(null);
    setLinkError(null);
  };

  return (
    <div className="space-y-4">
      {/* Shop Header - Liquid Glass with gradient */}
      <div className="glass-card p-4 animate-fadeInUp relative overflow-hidden">
        {/* Gradient overlay */}
        <div className="absolute inset-0 bg-gradient-to-br from-indigo-500/8 via-transparent to-indigo-400/5 pointer-events-none"></div>

        <div className="relative z-10 flex items-center gap-4">
          {/* Pet avatar with liquid ring */}
          <div className="liquid-avatar-ring">
            <div className="w-14 h-14 rounded-full bg-[var(--background)] overflow-hidden flex items-center justify-center">
              {hasPhoto ? (
                <img src={state.pet?.photo || ''} alt={state.pet?.name} className="w-full h-full object-cover" />
              ) : (
                <Clock className="w-7 h-7 text-[var(--foreground-secondary)]" />
              )}
            </div>
          </div>
          <div>
            <h3 className="font-semibold gradient-text">Presentes para {state.pet?.name || 'seu pet'}!</h3>
            <p className="text-sm text-[var(--foreground-secondary)]">
              {isPreloading ? (
                <span className="flex items-center gap-2">
                  <RefreshCw className="w-3 h-3 animate-spin text-indigo-400" />
                  <span className="text-indigo-400">Pré-carregando imagens...</span>
                </span>
              ) : autoGenerating ? (
                <span className="flex items-center gap-2">
                  <RefreshCw className="w-3 h-3 animate-spin text-indigo-400" />
                  <span className="text-indigo-400">Gerando previews com IA...</span>
                </span>
              ) : hasCachedImages ? (
                <span className="flex items-center gap-2">
                  <Sparkles className="w-3 h-3 text-emerald-400" />
                  <span className="text-emerald-400">Imagens prontas!</span>
                </span>
              ) : hasPhoto ? (
                'Veja como ficaria com cada brinquedo!'
              ) : (
                'Adicione uma foto para ver previews com IA'
              )}
            </p>
          </div>
        </div>
      </div>

      {/* Products - Liquid Glass Cards */}
      <div className="space-y-3">
        {SHOP_PRODUCTS.map((product, index) => {
          // Prioridade: 1) Preview salvo pelo usuário, 2) URL pré-cacheada, 3) Imagem original
          const savedPreview = state.productPreviews[product.id];
          const cachedUrl = getCachedImageUrl(product.id);
          const hasPreview = !!savedPreview || !!cachedUrl;
          const previewImg = savedPreview || cachedUrl || product.image;
          const isGenerating = generating === product.id;

          return (
            <div
              key={product.id}
              className="space-y-2 animate-fadeInUp"
              style={{ animationDelay: `${index * 100}ms` }}
            >
              <a
                href={product.link}
                target="_blank"
                rel="noopener noreferrer"
                className="glass-task flex items-center gap-3 p-3 group"
              >
                {/* Product image with glow effect */}
                <div className="w-16 h-16 rounded-xl bg-[var(--background-secondary)] overflow-hidden flex-shrink-0 relative shadow-lg group-hover:shadow-indigo-500/20 transition-shadow duration-300">
                  <ProductImage
                    src={previewImg}
                    alt={product.name}
                    hasPreview={hasPreview}
                  />
                  {hasPreview && (
                    <div className={`absolute bottom-0 right-0 text-xs px-1.5 py-0.5 rounded-tl-lg text-white font-medium ${
                      savedPreview ? 'bg-gradient-to-r from-purple-500 to-pink-500' : 'bg-gradient-to-r from-indigo-500 to-purple-500'
                    }`}>
                      {savedPreview ? '🎨 Custom' : '✨ IA'}
                    </div>
                  )}
                </div>

                <div className="flex-1 min-w-0 relative z-10">
                  <h4 className="font-medium text-sm group-hover:text-white transition-colors">{product.name}</h4>
                  <p className="text-xs text-gray-400 line-clamp-1">{product.description}</p>
                  <span className="text-emerald-400 font-bold">{product.price}</span>
                </div>

                {/* Badge */}
                <div className="absolute top-2 right-2 text-xs px-2.5 py-1 bg-indigo-500/15 rounded-full border border-indigo-500/25 text-indigo-400">
                  {product.badge}
                </div>
              </a>

              {aiConfigured && (
                <div className="flex gap-2">
                  {/* Botão geração automática */}
                  <button
                    onClick={() => handleGenerateImage(product.id, product.name, product.description)}
                    disabled={isGenerating || autoGenerating}
                    className="flex-1 glass-button flex items-center justify-center gap-2 py-2.5 px-3 rounded-xl text-sm transition-all disabled:opacity-50 group"
                  >
                    {isGenerating ? (
                      <>
                        <div className="w-4 h-4 border-2 border-indigo-400 border-t-transparent rounded-full animate-spin" />
                        <span className="text-indigo-400">Gerando...</span>
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-4 h-4 text-indigo-400 group-hover:text-indigo-300 transition-colors" />
                        <span className="text-indigo-400 group-hover:text-[var(--foreground)] transition-colors">
                          {hasPreview ? 'Gerar nova' : 'Gerar IA'}
                        </span>
                      </>
                    )}
                  </button>

                  {/* Botão para combinar imagens (quando tem foto do pet) */}
                  {hasPhoto && (
                    <button
                      onClick={() => openProductImageModal(product.id, product.name)}
                      disabled={isGenerating || autoGenerating}
                      className="glass-button flex items-center justify-center gap-2 py-2.5 px-3 rounded-xl text-sm transition-all disabled:opacity-50 group"
                      title="Envie uma foto do brinquedo real"
                    >
                      <Camera className="w-4 h-4 text-purple-400 group-hover:text-purple-300 transition-colors" />
                      <span className="text-purple-400 group-hover:text-[var(--foreground)] transition-colors">
                        Usar foto real
                      </span>
                    </button>
                  )}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Seção de Links Salvos do Mercado Livre */}
      {state.customProducts.length > 0 && (
        <div className="space-y-3 pt-4 border-t border-white/10">
          <h3 className="font-semibold text-sm text-[var(--foreground-secondary)] flex items-center gap-2">
            <Link2 className="w-4 h-4 text-yellow-400" />
            Meus Links Salvos
          </h3>
          {state.customProducts.map((product) => (
            <div key={product.id} className="relative group">
              <a
                href={product.url}
                target="_blank"
                rel="noopener noreferrer"
                className="glass-task flex items-center gap-3 p-3"
              >
                {/* Imagem do produto do ML */}
                <div className="w-16 h-16 rounded-xl bg-[var(--background-secondary)] overflow-hidden flex-shrink-0 relative shadow-lg">
                  {product.image ? (
                    <img
                      src={product.image}
                      alt={product.title}
                      className="w-full h-full object-cover"
                      onError={(e) => {
                        (e.target as HTMLImageElement).style.display = 'none';
                      }}
                    />
                  ) : (
                    <div className="w-full h-full flex items-center justify-center bg-gradient-to-br from-yellow-500/20 to-orange-500/20">
                      <Package className="w-6 h-6 text-yellow-400" />
                    </div>
                  )}
                  {/* Badge Mercado Livre */}
                  <div className="absolute bottom-0 right-0 text-[10px] bg-gradient-to-r from-yellow-500 to-yellow-400 px-1.5 py-0.5 rounded-tl-lg text-black font-bold">
                    ML
                  </div>
                </div>

                <div className="flex-1 min-w-0">
                  <h4 className="font-medium text-sm line-clamp-1">{product.title}</h4>
                  <p className="text-xs text-gray-400 line-clamp-1">{product.description}</p>
                  {product.price && (
                    <span className="text-emerald-400 font-bold">{product.price}</span>
                  )}
                </div>

                <ExternalLink className="w-4 h-4 text-[var(--foreground-secondary)] flex-shrink-0" />
              </a>

              {/* Botão de remover */}
              <button
                onClick={(e) => {
                  e.preventDefault();
                  e.stopPropagation();
                  removeCustomProduct(product.id);
                }}
                className="absolute -top-2 -right-2 w-6 h-6 bg-red-500 rounded-full flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity shadow-lg"
                title="Remover link"
              >
                <Trash2 className="w-3 h-3 text-white" />
              </button>
            </div>
          ))}
        </div>
      )}

      {/* Botão para adicionar novo link */}
      <button
        onClick={() => setShowAddLinkModal(true)}
        className="w-full glass-task p-4 flex items-center justify-center gap-2 group hover:border-yellow-400/30 transition-colors"
      >
        <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-yellow-500/20 to-orange-500/20 flex items-center justify-center">
          <Plus className="w-5 h-5 text-yellow-400" />
        </div>
        <div className="text-left">
          <p className="font-medium text-sm group-hover:text-white transition-colors">Adicionar link do Mercado Livre</p>
          <p className="text-xs text-[var(--foreground-secondary)]">Cole um link e veja o preview do produto</p>
        </div>
      </button>

      <p className="text-center text-xs text-[var(--foreground-secondary)] pt-2">
        Comprando aqui você ajuda o PetCare! 🐾
      </p>

      {/* Generated Image Modal - Liquid Glass */}
      {generatedImage && (
        <div
          className="fixed inset-0 glass-backdrop flex items-center justify-center z-50 p-4 animate-fadeIn"
          onClick={() => setGeneratedImage(null)}
        >
          <div
            className="glass-card p-5 max-w-sm w-full animate-fadeInUp"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Image with glow effect */}
            <div className="relative rounded-2xl overflow-hidden mb-4 shadow-2xl shadow-indigo-500/15">
              <img src={generatedImage.image} alt={generatedImage.productName} className="w-full" />
              <div className="absolute inset-0 bg-gradient-to-t from-black/40 to-transparent"></div>
            </div>

            <h3 className="text-center font-bold text-lg gradient-text mb-1">{state.pet?.name} adorou!</h3>
            <p className="text-center text-sm text-[var(--foreground-secondary)] mb-5">Imagem salva na loja!</p>

            <div className="flex gap-3">
              <button
                onClick={() => setGeneratedImage(null)}
                className="flex-1 py-3 glass-button rounded-xl hover:bg-white/10 transition-all font-medium"
              >
                Fechar
              </button>
              <a
                href={generatedImage.image}
                download={`${state.pet?.name}-${generatedImage.productName}.png`}
                className="flex-1 py-3 bg-gradient-to-r from-indigo-500 to-indigo-600 rounded-xl hover:from-indigo-400 hover:to-indigo-500 transition-all flex items-center justify-center gap-2 font-medium shadow-lg shadow-indigo-500/25"
              >
                <Download className="w-4 h-4" />
                Baixar
              </a>
            </div>
          </div>
        </div>
      )}

      {/* Modal para upload de imagem do produto - Combinar pet + brinquedo */}
      {productImageModal && (
        <div
          className="fixed inset-0 glass-backdrop flex items-center justify-center z-50 p-4 animate-fadeIn"
          onClick={() => {
            setProductImageModal(null);
            setCustomProductImage(null);
          }}
        >
          <div
            className="glass-card p-5 max-w-sm w-full animate-fadeInUp"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Header */}
            <div className="flex items-center justify-between mb-4">
              <h3 className="font-bold text-lg gradient-text">Criar cena especial</h3>
              <button
                onClick={() => {
                  setProductImageModal(null);
                  setCustomProductImage(null);
                }}
                className="p-1.5 rounded-lg hover:bg-white/10 transition-colors"
              >
                <X className="w-5 h-5 text-[var(--foreground-secondary)]" />
              </button>
            </div>

            <p className="text-sm text-[var(--foreground-secondary)] mb-4">
              Envie uma foto do brinquedo e veja {state.pet?.name} brincando com ele!
            </p>

            {/* Preview das duas imagens */}
            <div className="flex gap-4 mb-4">
              {/* Foto do pet */}
              <div className="flex-1">
                <p className="text-xs text-[var(--foreground-secondary)] mb-2 text-center">Seu pet</p>
                <div className="aspect-square rounded-xl overflow-hidden bg-[var(--background-secondary)] border border-white/10">
                  {state.pet?.photo ? (
                    <img src={state.pet.photo} alt={state.pet.name} className="w-full h-full object-cover" />
                  ) : (
                    <div className="w-full h-full flex items-center justify-center">
                      <Package className="w-8 h-8 text-[var(--foreground-secondary)]" />
                    </div>
                  )}
                </div>
              </div>

              {/* Ícone de união */}
              <div className="flex items-center">
                <div className="w-8 h-8 rounded-full bg-gradient-to-r from-indigo-500 to-purple-500 flex items-center justify-center">
                  <span className="text-white text-lg">+</span>
                </div>
              </div>

              {/* Foto do produto/brinquedo */}
              <div className="flex-1">
                <p className="text-xs text-[var(--foreground-secondary)] mb-2 text-center">Brinquedo</p>
                <div
                  className="aspect-square rounded-xl overflow-hidden bg-[var(--background-secondary)] border border-white/10 cursor-pointer hover:border-purple-400/50 transition-colors relative group"
                  onClick={() => productImageInputRef.current?.click()}
                >
                  {customProductImage ? (
                    <>
                      <img src={customProductImage} alt="Produto" className="w-full h-full object-cover" />
                      <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                        <Camera className="w-6 h-6 text-white" />
                      </div>
                    </>
                  ) : (
                    <div className="w-full h-full flex flex-col items-center justify-center gap-2 text-[var(--foreground-secondary)]">
                      <ImagePlus className="w-8 h-8" />
                      <span className="text-xs">Clique aqui</span>
                    </div>
                  )}
                </div>
              </div>
            </div>

            {/* Input de arquivo oculto */}
            <input
              ref={productImageInputRef}
              type="file"
              accept="image/*"
              onChange={handleProductImageUpload}
              className="hidden"
            />

            {/* Resultado esperado */}
            {customProductImage && (
              <div className="glass-task p-3 mb-4">
                <div className="flex items-center gap-2 text-sm">
                  <Sparkles className="w-4 h-4 text-indigo-400" />
                  <span className="text-[var(--foreground-secondary)]">
                    A IA vai criar uma cena de {state.pet?.name} brincando feliz com o brinquedo!
                  </span>
                </div>
              </div>
            )}

            {/* Botões */}
            <div className="flex gap-3">
              <button
                onClick={() => {
                  setProductImageModal(null);
                  setCustomProductImage(null);
                }}
                className="flex-1 py-3 glass-button rounded-xl hover:bg-white/10 transition-all font-medium"
              >
                Cancelar
              </button>
              <button
                onClick={handleCombineImages}
                disabled={!customProductImage || combiningImages}
                className="flex-1 py-3 bg-gradient-to-r from-purple-500 to-indigo-600 rounded-xl hover:from-purple-400 hover:to-indigo-500 transition-all flex items-center justify-center gap-2 font-medium shadow-lg shadow-purple-500/25 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {combiningImages ? (
                  <>
                    <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                    Criando...
                  </>
                ) : (
                  <>
                    <Sparkles className="w-4 h-4" />
                    Criar cena
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Modal para adicionar link do Mercado Livre */}
      {showAddLinkModal && (
        <div
          className="fixed inset-0 glass-backdrop flex items-center justify-center z-50 p-4 animate-fadeIn"
          onClick={closeAddLinkModal}
        >
          <div
            className="glass-card p-5 max-w-sm w-full animate-fadeInUp max-h-[90vh] overflow-y-auto"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Header */}
            <div className="flex items-center justify-between mb-4">
              <h3 className="font-bold text-lg gradient-text flex items-center gap-2">
                <Link2 className="w-5 h-5" />
                Adicionar Link
              </h3>
              <button
                onClick={closeAddLinkModal}
                className="p-1.5 rounded-lg hover:bg-white/10 transition-colors"
              >
                <X className="w-5 h-5 text-[var(--foreground-secondary)]" />
              </button>
            </div>

            <p className="text-sm text-[var(--foreground-secondary)] mb-4">
              Cole um link de produto do Mercado Livre para ver o preview com imagem.
            </p>

            {/* Input do link */}
            <div className="space-y-3">
              <div className="flex gap-2">
                <input
                  type="url"
                  value={linkUrl}
                  onChange={(e) => {
                    setLinkUrl(e.target.value);
                    setLinkError(null);
                  }}
                  placeholder="https://www.mercadolivre.com.br/..."
                  className="flex-1 px-4 py-3 rounded-xl bg-[var(--background-secondary)] border border-white/10 focus:border-yellow-400/50 focus:outline-none transition-colors text-sm"
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') {
                      fetchLinkPreview();
                    }
                  }}
                />
                <button
                  onClick={fetchLinkPreview}
                  disabled={loadingLink || !linkUrl.trim()}
                  className="px-4 py-3 bg-gradient-to-r from-yellow-500 to-orange-500 rounded-xl hover:from-yellow-400 hover:to-orange-400 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {loadingLink ? (
                    <Loader2 className="w-5 h-5 animate-spin" />
                  ) : (
                    <Link2 className="w-5 h-5" />
                  )}
                </button>
              </div>

              {/* Erro */}
              {linkError && (
                <p className="text-sm text-red-400 flex items-center gap-2">
                  <X className="w-4 h-4" />
                  {linkError}
                </p>
              )}

              {/* Preview do link */}
              {linkPreviewData && (
                <div className="glass-task p-4 space-y-3">
                  {/* Imagem */}
                  {linkPreviewData.image && (
                    <div className="relative aspect-video rounded-xl overflow-hidden bg-[var(--background-secondary)]">
                      <img
                        src={linkPreviewData.image}
                        alt={linkPreviewData.title}
                        className="w-full h-full object-contain"
                      />
                      <div className="absolute top-2 left-2 px-2 py-1 bg-yellow-400 rounded-lg">
                        <span className="text-xs font-bold text-black">Mercado Livre</span>
                      </div>
                    </div>
                  )}

                  {/* Info */}
                  <div>
                    <h4 className="font-semibold text-sm line-clamp-2">{linkPreviewData.title}</h4>
                    {linkPreviewData.description && (
                      <p className="text-xs text-[var(--foreground-secondary)] line-clamp-2 mt-1">
                        {linkPreviewData.description}
                      </p>
                    )}
                    {linkPreviewData.price && (
                      <p className="text-emerald-400 font-bold mt-2">{linkPreviewData.price}</p>
                    )}
                  </div>
                </div>
              )}
            </div>

            {/* Botões */}
            <div className="flex gap-3 mt-4">
              <button
                onClick={closeAddLinkModal}
                className="flex-1 py-3 glass-button rounded-xl hover:bg-white/10 transition-all font-medium"
              >
                Cancelar
              </button>
              <button
                onClick={handleAddCustomProduct}
                disabled={!linkPreviewData}
                className="flex-1 py-3 bg-gradient-to-r from-yellow-500 to-orange-500 rounded-xl hover:from-yellow-400 hover:to-orange-400 transition-all flex items-center justify-center gap-2 font-medium shadow-lg shadow-yellow-500/25 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <Plus className="w-4 h-4" />
                Salvar Link
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
